import time,sys,socket
print("\nWelcome to chating Application")
print("\nStarting.........")
time.sleep(1)
s=socket.socket()
host=socket.gethostname()
ip=socket.gethostbyname(host)
port=1111
s.bind((host,port))
print(host,",(",ip,")\n")
name=input("Enter Your Name: ")
s.listen(1)
print("waiting for connection........")
conn ,addr =s.accept()
print("\n Recived Connection from ",addr[0],"(",addr[1])
client_name=conn.recv(1024)
client_name=client_name.decode()
print(client_name," has connected")
conn.send(name.encode())
while True:
    message=input("Me: ")
    conn.send(message.encode())
    message=conn.recv(1024)
    message=message.decode()
    print(client_name,": ",message)